# Generated by Django 2.1.2 on 2019-03-12 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('label', models.IntegerField(choices=[(1, 'system'), (2, 'created'), (3, 'edited'), (4, 'deleted')], default=1)),
                ('actor_name', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
                ('locked', models.BooleanField(blank=True, default=False)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('actor_name',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(1, 'system'), (2, 'created'), (3, 'edited'), (4, 'deleted')], default=1)),
                ('role_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='actors.Actor')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('actor', 'role_name'),
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(1, 'system'), (2, 'created'), (3, 'edited'), (4, 'deleted')], default=1)),
                ('synonym', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='actors.Actor')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('actor', 'synonym'),
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(1, 'system'), (2, 'created'), (3, 'edited'), (4, 'deleted')], default=1)),
                ('wikilink', models.CharField(max_length=500)),
                ('rank', models.IntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikis', to='actors.Actor')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('actor', 'rank'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='wiki',
            unique_together={('actor', 'wikilink')},
        ),
        migrations.AlterUniqueTogether(
            name='synonym',
            unique_together={('actor', 'synonym')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('actor', 'role_name')},
        ),
    ]
