# Generated by Django 2.1.2 on 2018-10-25 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikis', to='actors.Actor'),
        ),
    ]
